-- =========================================================
-- GUIA DO INSPETOR PADRÃO - SEED DE PROCEDIMENTOS
-- Migra o banco de procedimentos (consulta de normas) do JS para o Supabase.
-- Rode DEPOIS de 04_inspecoes_procedimentos_rls.sql.
-- Reexecutável: limpa e reinsere.
-- =========================================================

delete from public.procedimentos;

insert into public.procedimentos
  (area_key, area_nome, area_icone, item_key, titulo, codigo, descricao, ordem)
values
  ('amv', 'AMV & Componentes', '⚙️', 'agulha', 'Ponta da Agulha (Perfil 5100)', 'ETMs 0005, 0007, 0008, 0009', 'Meça a espessura da ponta da agulha a exatos 15mm do início da usinagem. O desgaste não pode exceder o estipulado. Tolerância máxima: 3.9mm (Nominal AREMA: 3.1mm + Tol: 0.8mm). Valores entre 3.7mm e 3.9mm exigem monitoramento programado. Acima de 3.9mm há risco de descarrilamento: bloquear e substituir.', 10),
  ('amv', 'AMV & Componentes', '⚙️', 'rolete', 'Roletes (Viga I)', 'EM-SPE-072 (Item 5.2)', 'Altura máxima do rolete em relação à base da agulha: ≤ 2.0mm. Acima desse valor necessita calibração pela equipe de via.', 20),
  ('amv', 'AMV & Componentes', '⚙️', 'coxin', 'Coxins dos Roletes (Dureza)', 'EM-SPE-072 (Item 5.3.1)', 'Dureza Shore A do coxin deve estar entre 88 e 92. Fora dessa faixa, rejeitar lote de coxins e retornar ao fornecedor.', 30),
  ('amv', 'AMV & Componentes', '⚙️', 'jacare_canal', 'Jacaré (Profundidade do Canal)', 'ETMs 0005, 0007, 0008, 0009', 'Profundidade do canal deve ser aferida no núcleo do jacaré de aço manganês: 53 ± 2 mm (faixa 51 a 55 mm). Fora da tolerância: solicitar esmerilhamento ou preenchimento de solda.', 40),
  ('amv', 'AMV & Componentes', '⚙️', 'jacare_dureza', 'Jacaré (Dureza Brinell)', 'ETMs 0008, 0009', 'Dureza Brinell na área de impacto: 352 a 418 HB. Fora da tolerância exigida: bloquear lote do Jacaré e abrir RNC.', 50),
  ('amv', 'AMV & Componentes', '⚙️', 'fixacao_concreto', 'Fixação AMV Concreto (Pressão Grampo)', 'ENG-DSV-VP-ETM-A0019', 'Pressão do Grampo Eclip-2009: 1200 ± 300 kgf (faixa 900 a 1500 kgf). Fora da faixa: substituir grampos fadigados na região.', 60),
  ('amv', 'AMV & Componentes', '⚙️', 'cilindro', 'Cilindro de Mola', 'EM-SPE-026', 'Pressão mínima de travamento: 500 kgf. Tempo de acionamento com 260 kg: entre 10 e 12 segundos. Fora da norma: ajuste de válvula do cilindro pela manutenção.', 70),
  ('amv', 'AMV & Componentes', '⚙️', 'batefica', 'Aparelho Talonável Bate-Fica', 'EM-SPE-017', 'Deslocamento verificado das agulhas: 100 a 121 mm. Fora da tolerância: calibrar hastes do aparelho Bate-Fica.', 80),
  ('brita', 'Brita para Lastro', '🪨', 'visual', 'Inspeção Visual (Contaminação)', 'MAN-VP-T-ETM-ES-0006-05', 'Verificar presença visível de argila, areia ou matéria orgânica no lastro. Qualquer contaminação visível resulta em rejeição imediata do vagão (REFUGO). Lastro limpo = liberado para aplicação.', 10),
  ('brita', 'Brita para Lastro', '🪨', 'forma_lote', 'Ensaio de Forma (Lote / Não-Cúbicas)', 'MAN-VP-T-ETM-ES-0006-05', 'Índice máximo de britas não-cúbicas permitido: 15%. Britas lamelares ou alongadas reduzem o intertravamento do lastro. Acima de 15%: lote reprovado, solicitar nova britagem.', 20),
  ('brita', 'Brita para Lastro', '🪨', 'granulometria', 'Ensaio de Granulometria (AREMA 24)', 'MAN-VP-T-ETM-ES-0006-05 / Plano 24 AREMA', 'Percentuais Retidos Acumulados: Peneira 3" (76.2 mm) = 0%; Peneira 2.1/2" (63.5 mm) = 0% a 10%; Peneira 1.1/2" (38.1 mm) = 40% a 75%; Peneira 3/4" (19.1 mm) = 90% a 100%; Peneira 1/2" (12.7 mm) = 95% a 100%. Fora dessas faixas: lote reprovado.', 30),
  ('brita', 'Brita para Lastro', '🪨', 'laboratorio', 'Ensaios Físicos (Laboratório)', 'MAN-VP-T-ETM-ES-0006-05', 'Abrasão Los Angeles: máximo 35% para granito, 30% para calcário/basalto. Material Pulverulento: máximo 1%. Torrões de Argila: máximo 0.5%. Falha em qualquer um: bloquear pedreira/veio para fornecimento.', 40),
  ('concreto', 'Dormente de Concreto', '🧱', 'vazio_apoio', 'Vazios - Apoio do Trilho', 'PO-SPE-160 (Tabela 1)', 'Aceitável: Profundidade ≤2 mm, Comprimento ≤3 mm, Largura ≤3 mm. Reparável: 3-5 mm de profundidade, 4-10 mm comprimento, 4-10 mm largura (reparo com argamassa epóxi). Refugo: >6 mm de profundidade.', 10),
  ('concreto', 'Dormente de Concreto', '🧱', 'vazio_fora_apoio', 'Vazios - Fora da Região do Trilho', 'PO-SPE-160 (Tabela 2)', 'Aceitável: Profundidade ≤5 mm, Comprimento ≤5 mm, Altura ≤5 mm. Reparável: 6-10 mm de profundidade, 6-20 mm comp/alt. Refugo: >11 mm de profundidade.', 20),
  ('concreto', 'Dormente de Concreto', '🧱', 'vazio_testeira', 'Vazios - Testeira', 'PO-SPE-160 (Página 15-16)', 'Com exposição de armadura: tolerável até 30 mm de profundidade. Sem exposição: reparável até 50 mm. Acima desses limites: segregar dormente e preencher RNC.', 30),
  ('concreto', 'Dormente de Concreto', '🧱', 'quebra_lat_sup', 'Quebras - Laterais / Superior', 'PO-SPE-160 (Tabela 3)', 'Aceitável: Prof. ≤10 mm, Comp. ≤49 mm, Alt. ≤29 mm. Reparável: Prof. 11-20 mm, Comp. 50-200 mm, Alt. 30-150 mm. Refugo: >21 mm de profundidade ou exposição de armadura ativa.', 40),
  ('concreto', 'Dormente de Concreto', '🧱', 'quebra_testeira', 'Quebras - Testeira', 'PO-SPE-160 (Tabela 4)', 'Aceitável: Prof. ≤10 mm, Comp. ≤49 mm, Alt. ≤29 mm. Reparável: Prof. 11-20 mm, Comp. 50-200 mm, Alt. 30-150 mm. Qualquer exposição de armadura ativa = refugo.', 50),
  ('concreto', 'Dormente de Concreto', '🧱', 'fissura_ombreira', 'Fissuras - Ombreira', 'PO-SPE-160 (Tabela 5)', 'Qualquer fissura na ombreira = refugo sumário. Não há tolerância para esse tipo de defeito.', 60),
  ('concreto', 'Dormente de Concreto', '🧱', 'fissura_lateral', 'Fissuras - Lateral / Transversal', 'PO-SPE-160 (Tabela 5)', 'Aceitável: Espessura ≤0,10 mm e Comprimento ≤10 mm. Reparável: Espessura 0,15-0,50 mm e Comprimento 11-100 mm (injeção de epóxi). Refugo: Espessura ≥0,55 mm ou Comprimento >101 mm.', 70),
  ('madeira', 'Dormente de Madeira', '🪵', 'fisico', 'Propriedades Físicas e Químicas', 'MAN-DM-T-MTE-DM-0001', 'Umidade máxima: 30%. Densidade mínima 1ª Classe: 750 kg/m³. Densidade mínima 2ª Classe: 600 kg/m³. Retenção CCA mínima: 9.6 kg/m³. Fora desses limites: recusar recebimento (falha no tratamento).', 10),
  ('madeira', 'Dormente de Madeira', '🪵', 'dimensoes', 'Dimensões Fora do Padrão', 'MAN-DM-T-MTE-DM-0001', 'Tolerância Comprimento: +5 cm / -0 cm do nominal. Tolerância Largura: ±2 cm. Tolerância Altura: ±1 cm. Fora dessas tolerâncias: dormente dimensionalmente divergente, refugo.', 20),
  ('madeira', 'Dormente de Madeira', '🪵', 'esmoado', 'Esmoado (Falta de Canto)', 'MAN-DM-T-MTE-DM-0001', 'Fora da zona de fixação (2,00 m): Face Reta ≥9 cm, Topo ≥15 cm. Dentro da zona de fixação (2,00 m): Face Reta ≥14 cm, Topo ≥20 cm. Para 2,20/2,80 m os limites aumentam em 1-2 cm. Abaixo desses mínimos: segregar.', 30),
  ('madeira', 'Dormente de Madeira', '🪵', 'racha_topo', 'Fenda ou Racha de Topo', 'MAN-DM-T-MTE-DM-0001', 'Comprimento máximo: 15 cm. Abertura máxima: 2 mm. Proibida presença na zona de fixação. Excedeu limites: segregar dormente.', 40),
  ('madeira', 'Dormente de Madeira', '🪵', 'racha_centro', 'Rachadura de Centro', 'MAN-DM-T-MTE-DM-0001', 'Comprimento máximo: 15 cm. Abertura máxima: 2 mm. Profundidade máxima: 2 cm. Proibida presença na zona de fixação. Excedeu limites: segregar dormente.', 50),
  ('madeira', 'Dormente de Madeira', '🪵', 'furos_nos', 'Furos de Broca / Nós Cariados', 'MAN-DM-T-MTE-DM-0001', 'Diâmetro máximo: 2,5 cm. Profundidade máxima: menor que 5 cm. Proibida presença na zona de fixação. Excedeu limites: segregar dormente.', 60),
  ('madeira', 'Dormente de Madeira', '🪵', 'empenamento', 'Empenamento (Flecha)', 'MAN-DM-T-MTE-DM-0001', 'Flecha máxima permitida: metade do comprimento do dormente em cm (ex.: 2,00 m → máx 1 cm; 4,00 m → máx 2 cm). Acima: segregar para descarte.', 70),
  ('madeira', 'Dormente de Madeira', '🪵', 'podre', 'Madeira Podre', 'MAN-DM-T-MTE-DM-0001', 'Refugo Sumário: dormente com aspecto de apodrecimento é rejeitado imediatamente, sem análise dimensional. Não aceitável em nenhuma hipótese.', 80),
  ('madeira', 'Dormente de Madeira', '🪵', 'casca', 'Presença de Casca', 'MAN-DM-T-MTE-DM-0001', 'Refugo Sumário: presença de casca na madeira é rejeitada imediatamente. Indica falha no processamento inicial da tora.', 90),
  ('madeira', 'Dormente de Madeira', '🪵', 'anti_rachante', 'Falta de Proteção Anti-Rachante', 'MAN-DM-T-MTE-DM-0001', 'Refugo Sumário: proteção anti-rachante ausente ou menor que 70% na face do dormente é rejeitado imediatamente.', 100),
  ('madeira', 'Dormente de Madeira', '🪵', 'amarracao', 'Falha na Amarração do Fardo', 'MAN-DM-T-MTE-DM-0001', 'Refugo Sumário: amarração deficiente (menos de 3 fitas ou sem pontaletes) resulta em rejeição imediata do fardo.', 110),
  ('sub', 'Subcomponentes Metálicos/Plásticos', '🔩', 'pal_branca_tr68', 'Palmilha Branca TR68 FAST-CLIP (SAP:109105)', 'ENG-DVP-D183 / INF-FX-0003', 'Medida 1: 187,5 a 191,5 mm. Medida 2: 151 a 155 mm. Medida 3: 111,5 a 114,5 mm. Medida 4: 5,5 a 7,5 mm. Fora das tolerâncias: lote dimensionalmente reprovado, preencher RNC.', 10),
  ('sub', 'Subcomponentes Metálicos/Plásticos', '🔩', 'pal_verde_uic60', 'Palmilha Verde UIC60 (SAP:127543)', 'ENG-DVP-D135 / INF-FX-0003', 'Medida 1: 148,5 a 150 mm. Medida 2: 113 a 114 mm. Medida 3: 7,05 a 7,55 mm. Fora das tolerâncias: lote dimensionalmente reprovado, preencher RNC.', 20),
  ('sub', 'Subcomponentes Metálicos/Plásticos', '🔩', 'iso_verde_3510w', 'Isolador Lateral Verde 3510W (SAP:127551)', 'ENG-DVP-D136', 'Medida 1: 61,5 a 63 mm. Medida 2: 9,6 a 10,2 mm. Medida 3: 7,4 a 8 mm. Fora das tolerâncias: lote dimensionalmente reprovado.', 30),
  ('sub', 'Subcomponentes Metálicos/Plásticos', '🔩', 'iso_amarelo_3510w', 'Isolador Lateral Amarelo 3510W (SAP:147554)', 'ENG-DVP-D136', 'Medida 1: 61,5 a 63 mm. Medida 2: 9,6 a 10,2 mm. Medida 3: 7,4 a 8 mm. Fora das tolerâncias: lote dimensionalmente reprovado.', 40),
  ('sub', 'Subcomponentes Metálicos/Plásticos', '🔩', 'iso_preto_3502w', 'Isolador Lateral Preto 3502W (SAP:147555)', 'ENG-DVP-D084', 'Medida 1: 61,5 a 63 mm. Medida 2: 7,6 a 8,2 mm. Medida 3: 7,4 a 8 mm. Fora das tolerâncias: lote dimensionalmente reprovado.', 50),
  ('sub', 'Subcomponentes Metálicos/Plásticos', '🔩', 'iso_branco_pandrol', 'Isolador Lateral Branco 8mm (PANDROL - SAP:121107)', 'ENG-DVP-D084', 'Medida 1: 61,5 a 63 mm. Medida 2: 7,6 a 8,2 mm. Medida 3: 7,4 a 8 mm. Fora das tolerâncias: lote dimensionalmente reprovado.', 60),
  ('sub', 'Subcomponentes Metálicos/Plásticos', '🔩', 'iso_branco_3502w', 'Isolador Lateral Branco 3502W (SAP:121107)', 'ENG-DVP-D084', 'Medida 1: 61,5 a 63 mm. Medida 2: 7,6 a 8,2 mm. Medida 3: 7,4 a 8 mm. Fora das tolerâncias: lote dimensionalmente reprovado.', 70),
  ('sub', 'Subcomponentes Metálicos/Plásticos', '🔩', 'usp_getzner', 'UNDER SLEEPER PAD - USP (GETZNER - SAP:126980)', 'ENG-DVP-D131', 'Comprimento: 1360 a 1390 mm. Largura: 225 a 245 mm. Espessura: 7 a 11 mm. Fora das tolerâncias: lote dimensionalmente reprovado, preencher RNC.', 80),
  ('sub', 'Subcomponentes Metálicos/Plásticos', '🔩', 'grampo_capa_branca', 'Grampo W c/ isolador Capa Branca (SAP:99604)', 'ENG-DVP-T040', 'Medida 1: 106,5 a 111 mm. Medida 2: 15,75 a 16,25 mm. Medida 3: 74,5 a 79 mm. Fora das tolerâncias: lote dimensionalmente reprovado.', 90),
  ('sub', 'Subcomponentes Metálicos/Plásticos', '🔩', 'grampo_iso_frontal', 'Grampo W c/ isolador frontal (SAP:99604)', 'ENG-DVP-T040', 'Medida 1: 106,5 a 111 mm. Medida 2: 15,75 a 16,25 mm. Medida 3: 74,5 a 79 mm. Fora das tolerâncias: lote dimensionalmente reprovado.', 100),
  ('sub', 'Subcomponentes Metálicos/Plásticos', '🔩', 'ombreira_eclip', 'Ombreira E-CLIP HFOB02 (SAP:127542)', 'ENG-DVP-D139', 'Medida 1: 73,5 a 76,5 mm. Medida 2: mínimo 24 mm (sem limite superior). Fora das tolerâncias: lote dimensionalmente reprovado, preencher RNC.', 110),
  ('sub', 'Subcomponentes Metálicos/Plásticos', '🔩', 'ombreira_fastclip', 'Ombreira FAST-CLIP HFOB08 (SAP:127406B)', 'ENG-DVP-D074', 'Medida 1: 99,75 a 102,25 mm. Medida 2: 58,7 a 60,7 mm. Medida 3: 95,9 a 98,1 mm. Medida 4: 70,3 a 72,5 mm. Medida 5: 34,9 a 36,7 mm. Fora das tolerâncias: reprovar lote.', 120),
  ('sub', 'Subcomponentes Metálicos/Plásticos', '🔩', 'pal_verde_almofada', 'Palmilha Verde Almofada 6980 (SAP:127543)', 'ENG-DVP-D135', 'Medida 1: 148,5 a 150 mm. Medida 2: 113 a 114 mm. Medida 3: 7,05 a 7,55 mm. Fora das tolerâncias: lote dimensionalmente reprovado.', 130),
  ('sub', 'Subcomponentes Metálicos/Plásticos', '🔩', 'pal_branca_almofada', 'Palmilha Branca Almofada 7552 (SAP:109105)', 'ENG-DVP-D183', 'Medida 1: 187,5 a 191,5 mm. Medida 2: 151 a 155 mm. Medida 3: 111,5 a 114,5 mm. Medida 4: 5,5 a 7,5 mm. Fora das tolerâncias: lote dimensionalmente reprovado.', 140);
